version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies with Yarn..."
      - yarn install

  build:
    commands:
      - echo "Building the project..."
      - yarn build

  post_build:
    commands:
      - echo "Build complete."

artifacts:
  files:
    - '**/*'
  base-directory: .next
